---
title: Python高级用法
date: 2018-04-10
tags:
    - python
---

本文简单介绍一下Python的高级用法，包括yield，with使用，`__init__, __new__, __call__`函数的使用，python静态方法和类方法的区别

<!-- more -->

## 1. Python with使用

### 1.1 理解with逻辑
有一些任务，可能事先需要设置，事后做清理工作。对于这种场景，Python的with语句提供了一种非常方便的处理方式。一个很好的例子是文件处理，你需要获取一个文件句柄，从文件中读取数据，然后关闭文件句柄。
如果不用with语句，代码如下：
```python
file = open("/tmp/foo.txt")
data = file.read()
file.close()
```

这里有两个问题。一是可能忘记关闭文件句柄；二是文件读取数据发生异常，没有进行任何处理。下面是处理异常的加强版本：
```python
file = open("/tmp/foo.txt")
try:
    data = file.read()
finally:
    file.close()
```

虽然这段代码运行良好，但是太冗长了。这时候就是with一展身手的时候了。除了有更优雅的语法，with还可以很好的处理上下文环境产生的异常。下面是with版本的代码：
```python
with open("/tmp/foo.txt") as file:
    data = file.read()
```

### 1.2 with如何工作的
with如何工作？

这看起来充满魔法，但不仅仅是魔法，Python对with的处理还很聪明。基本思想是with所求值的对象必须有一个`__enter__()`方法，一个`__exit__()`方法。
紧跟with后面的语句被求值后，返回对象的`__enter__()`方法被调用，这个方法的返回值将被赋值给as后面的变量。当with后面的代码块全部被执行完之后，将调用前面返回对象的`__exit__()`方法。

下面例子可以具体说明with如何工作：
```python
#!/usr/bin/env python
# with_example01.py
 
class Sample:
    def __enter__(self):
        print "In __enter__()"
        return "Foo"
 
    def __exit__(self, type, value, trace):
        print "In __exit__()"
 
def get_sample():
    return Sample()
 
with get_sample() as sample:
    print "sample:", sample
```

```bash
代码输出结果如下：
In __enter__()
sample: Foo
In __exit__()
```

正如你看到的，
1. `__enter__()`方法被执行
2. `__enter__()`方法返回的值 - 这个例子中是"Foo"，赋值给变量'sample'
3. 执行代码块，打印变量"sample"的值为 "Foo"
4. `__exit__`方法被调用

with真正强大之处是它可以处理异常。可能你已经注意到Sample类的exit方法有三个参数- val, type 和 trace。 这些参数在异常处理中相当有用。我们来改一下代码，看看具体如何工作的。
```python
#!/usr/bin/env python
# with_example02.py
 
class Sample:
    def __enter__(self):
        return self
 
    def __exit__(self, type, value, trace):
        print "type:", type
        print "value:", value
        print "trace:", trace
 
    def do_something(self):
        bar = 1/0
        return bar + 10
 
with Sample() as sample:
    sample.do_something()
```

代码运行结果如下：
```bash
bash-3.2$ ./with_example02.py
type: <type 'exceptions.ZeroDivisionError'>
value: integer division or modulo by zero
trace: <traceback object at 0x1004a8128>
Traceback (most recent call last):
  File "./with_example02.py", line 19, in <module>
    sample.do_something()
  File "./with_example02.py", line 15, in do_something
    bar = 1/0
ZeroDivisionError: integer division or modulo by zero
```

这个例子中，with后面的get_sample()变成了Sample()。这没有任何关系，只要紧跟with后面的语句所返回的对象有`__enter__()`和`__exit__`方法即可。此例中，Sample()的`__enter__()`方法返回新创建的Sample对象，并赋值给变量sample。
实际上，在with后面的代码块抛出任何异常时，`__exit__`方法被执行。正如例子所示，异常抛出时，与之关联的type，value和stack trace传给`__exit__`方法，因此抛出的ZeroDivisionError异常被打印出来了。开发库时，清理资源，关闭文件等等操作，都可以放在`__exit__`方法当中。
因此，Python的with语句是提供一个有效的机制，让代码更简练，同时在异常产生时，清理工作更简单

## 2. Python `__init__, __new__, __call__`方法
- `__new__`： 对象的创建，是一个静态方法，第一个参数是cls。(想想也是，不可能是self，对象还没创建，哪来的self)，返回一个对象
- `__init__`： 对象的初始化， 是一个实例方法，第一个参数是self。
- `__call__`： 对象可call，注意不是类，实例化后的对象，被当做函数调用时，执行该函数

```python
class Bar(object):
    def __new__(cls, *args):
        self = super(Bar, cls).__new__(cls)
        #self = super().__new__(cls) #py3
        print '__new__'
        return self

    def __init__(self, *args):
        print '__init__'
        self.name = args[0]

    def __call__(self, *args):
        print '__call__', args

```
测试如下
```bash
#执行
b = Bar('haha')
print b.name
b()

# 输出如下结果
__new__
__init__
hah
__call__ ()
```

## 3. Python 类方法和静态方法区别

区别：
> 类方法的第一个参数必须是cls，静态方法没要求

类方法应用（模拟构造函数）
```python

class Book(object):

    def __init__(self, title):
        self.title = title

    @classmethod
    def create(cls, title):
        book = cls(title=title)
        return book

book1 = Book("python")
book2 = Book.create("python and django")
print(book1.title)
print(book2.title)
```

`参考文献`
- https://www.jianshu.com/p/c00df845323c
